### ISSUE TITLE
Yield farming rewards and NFT staked are not shown until SignIn

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#23]
When the user has not Signed In the NFT staked and ENTR rewards are not shown

![image](https://user-images.githubusercontent.com/12232750/150140796-fef2da39-b99f-4fab-ad13-d7fbed357ec8.png)

**Comment by taskudis** [comment]
Fixed at 5859950153b3812b971ad1d7e707ce2c4b1102e2
