### ISSUE TITLE
Transactions Tab in LandWorks YF should have My TX and All TX and should show LandWorks TX only

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#24]
Right now:
![image](https://user-images.githubusercontent.com/12232750/150141794-a219c9f8-0b1f-4ba1-856b-1df4c6cbd076.png)
Expected:
![image](https://user-images.githubusercontent.com/12232750/150141897-b88e213b-a9da-47e1-9ec0-815374294c16.png)

**Comment by strenev** [comment]
<img width="1199" alt="Screenshot 2022-01-20 at 11 28 14" src="https://user-images.githubusercontent.com/8581537/150311332-fa7bd86d-75b0-4eb1-9551-e04af8f97769.png">

Fixed and deployed.
