### ISSUE TITLE
Custom text when no LandWorks NFTs have been staked

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#25]
Add "You don't have any LandWorks NFTs staked" text in the Unstake view:
![image](https://user-images.githubusercontent.com/12232750/150142651-e830e427-dad6-4012-8e82-2a9d6f9761fa.png)

**Comment by Daniel-K-Ivanov** [comment]
Maybe we can use this element to show that info:
![image](https://user-images.githubusercontent.com/12232750/150146605-42f6cc53-8cbf-4fc6-b99e-eaa9fdb2dfd4.png)

**Comment by strenev** [comment]
<img width="731" alt="Screenshot 2022-01-19 at 21 17 18" src="https://user-images.githubusercontent.com/8581537/150199350-05038c42-4374-4aa1-a0ff-890c2b8be634.png">

fixed and deployed on https://landworks-yf.web.app/
