### ISSUE TITLE
The list with NFTs is broken

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#26]
Notice that there are gray lines in the bottom and the right of the component. They should not be there 
![image](https://user-images.githubusercontent.com/12232750/150142746-2b0bd3d5-5b55-406b-be9a-5f7baebd7317.png)

**Comment by Daniel-K-Ivanov** [comment]
No longer reproducing

**Comment by Daniel-K-Ivanov** [comment]
it is reproducing again

**Comment by strenev** [comment]
What browser are you using to reproduce it?

**Comment by Daniel-K-Ivanov** [comment]
![image](https://user-images.githubusercontent.com/12232750/150375569-7f1fcf1f-fa03-4075-9787-83ea4fb1fdab.png)
