### ISSUE TITLE
Custom text when user does not have any LandWorks NFTs

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#29]
Add "You don't have any LandWorks NFTs to stake" text in the Stake view

![image](https://user-images.githubusercontent.com/12232750/150146012-698c8b91-355c-4c60-a6e8-6e68ef36d06c.png)

**Comment by Daniel-K-Ivanov** [comment]
Maybe we can use this element to show that info:
![image](https://user-images.githubusercontent.com/12232750/150146605-42f6cc53-8cbf-4fc6-b99e-eaa9fdb2dfd4.png)

**Comment by strenev** [comment]
<img width="731" alt="Screenshot 2022-01-19 at 21 31 40" src="https://user-images.githubusercontent.com/8581537/150201156-c46ac733-b07a-4c5c-b740-e0bde0a78696.png">

fixed and deployed to https://landworks-yf.web.app/yield-farming
