### ISSUE TITLE
"Enable LandWorks NFTs" is shown as disabled when user has executed approval

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#30]
The button should not be shown if the user already approved the address

![image](https://user-images.githubusercontent.com/12232750/150164327-148bcb5e-0daa-4ac3-a122-8e1f65358f20.png)

**Comment by taskudis** [comment]
Fixed c7c03f8e866081896442764f6e9a8ff2b9484e9c
