### ISSUE TITLE
"Enable LandWorks NFTs" button is shown again after 1 NFT has been staked

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#31]
Once one NFT has been staked, the button for "Enable LandWorks NFTs" is shown again

1. Connect wallet that has more than 1 landworks nfts
2. Stake 1
3. notice that the Enable landworks nfts button is enabled after the tx is mined even though you already approved the address and even staked one NFT
![image](https://user-images.githubusercontent.com/12232750/150164955-70a2fd27-569f-4588-a019-e7aa490efe56.png)

**Comment by taskudis** [comment]
@Daniel-K-Ivanov Cannot reproduce on 6d840cb393430b25b0b44940e5816ebee12d17cf
