### ISSUE TITLE
Current reward number is not formatted properly

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#32]
![image](https://user-images.githubusercontent.com/12232750/150165104-73088d07-96dc-4e96-867c-5051d18fb3ee.png)

**Comment by strenev** [comment]
<img width="731" alt="Screenshot 2022-01-19 at 21 41 32" src="https://user-images.githubusercontent.com/8581537/150202438-76763267-fd01-4aa7-9be4-19a9919ea9be.png">

fixed and deployed to https://landworks-yf.web.app/
