### ISSUE TITLE
LandWorks NFTs (Staked tab)

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#33]
When switching between accounts in Metamask, LandWorks NFTs are changed correctly unless I do the following:
1. Connect with an address that has LandWorks NFTs (not staked yet)
2. From metamask, click and change the address to an address that does not have LandWorks NFTs
Notice that the state does not change and we are showing the same NFts from the previous address

**Comment by strenev** [comment]
This seems to be fixed from this commit - https://github.com/EnterDAO/ENTER-DAO-GOV-YF-Frontend/pull/22/commits/e8a3fb8121d3a1ed0d74821f45175c5b880e9f76
