### ISSUE TITLE
"Enable LandWorks NFTs" button is not consistent with Stake button

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#34]
The stake button has
- a loader while TX is executing
- has a popup showing the Etherscan Link 

The Enable Landworks NFTs does not show a loader nor a popup

**Comment by taskudis** [comment]
Added loading state in a0f9dbf2bdc3c52781c2d4533be487b30ae91a85
