### ISSUE TITLE
"My Stake" section is not updated after TX is executed while the rest of the view is

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#35]
Execute a Stake or Unstake TX. Notice that the view for Stake/Unstake is updated however My Stake section is not

**Comment by strenev** [comment]
This is fixed and deployed, however, we still have the lag from The Graph sometimes. I can spend more time fine-tuning it, maybe after release.
