### ISSUE TITLE
Staked NFTs shows the staked parcels actually and not the LandWorks NFTs

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/ENTER-DAO-GOV-YF-Frontend#38]
1. Prior to staking the Staked NFTs was showing `5`
2. I staked 1 estate with `5` LANDs in it and the Staked NFTs went to `10`

Expected behaviour:
- The `Staked NFTs` should show the number of `LandWorks NFTs` that the staking contract owns (have been staked so far) and not the number of parcels
- Lets change the label of `Staked NFTs` to

```
Staked NFTs
5 representing 10 parcels
```

![image](https://user-images.githubusercontent.com/12232750/150343294-f08daa79-f99e-4349-ac69-ac4089ae6d6b.png)

**Comment by strenev** [comment]
Should be fixed and deployed. Instead of calling totalSupply on the yield farming contract, now we call balanceOf(yfContact.address) on the landworks contract
